_wandb:
    value:
        cli_version: 0.25.0
        e:
            ixbfy1tqiwjj6i2fllt1pzeoco1y17ls:
                args:
                    - task=tsp
                    - model=granite
                    - train=dpo
                    - cluster=example
                    - gpu_nums=0
                    - prefix=wandb_smoketest
                    - seed=0
                    - wandb=1
                    - project=EvoTune
                    - entity=zeio99guo-institut-polytechnique-de-paris
                    - num_rounds=500
                    - num_cont_rounds=100
                    - use_vllm=0
                    - use_tgi=0
                codePath: src/experiments/main.py
                codePathLocal: src/experiments/main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "177597018112"
                executable: /mnt/e/currentWORK/AAA_LCM/EvoTune/.venv/bin/python
                git:
                    commit: 7ca349d1ec8b788e4fcc7d29d6be00251ac71750
                    remote: https://github.com/zihao-guo/EvoTune.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-f05e3b25-a13e-c5d4-c7e5-bcd2c5f25c4a
                host: ZihaoPC
                memory:
                    total: "16670449664"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/e/currentWORK/AAA_LCM/EvoTune/src/experiments/main.py
                python: CPython 3.11.14
                root: /mnt/e/currentWORK/AAA_LCM/EvoTune
                startedAt: "2026-03-03T11:51:44.812015Z"
                writerId: ixbfy1tqiwjj6i2fllt1pzeoco1y17ls
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 51
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 51
                - 71
                - 84
                - 95
                - 98
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "6": 4.57.6
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
accelerate_config:
    value: 1gpu_0
cluster:
    value:
        scratch_path: /path/to/scratch
        use_tgi: 0
        use_vllm: 1
creative_prompt:
    value: 1
descending_order:
    value: 1
entity:
    value: zeio99guo-institut-polytechnique-de-paris
eval_frequency:
    value: 100
evalset:
    value: trainperturbedset
final_percentile:
    value: 0.2
finetuning_frequency:
    value: 400
flash_attn:
    value: 0
full_accelerate_config:
    value: ./configs/accelerate_config/1gpu_0.yaml
full_model_name:
    value: ibm-granite/granite-3.1-2b-instruct
function_str_to_extract:
    value: heuristics
gpu_nums:
    value: 0
group_name:
    value: wandb_smoketest/tsp_granite_dpo
initial_percentile:
    value: 0.6
logs_dir:
    value: out/logs/wandb_smoketest/tsp_tsp_granite_dpo_0
logs_path:
    value: .
lora_config:
    value:
        lora_alpha: 32
        r: 64
lr_annealing:
    value: 0
max_loops:
    value: 1
model:
    value:
        max_tokens: 2048
        model_name: granite
        temperature: 0.9
        topk: 100
        topp: 0.95
model_adapter_dir:
    value: out/logs/wandb_smoketest/tsp_tsp_granite_dpo_0/model_adapter_granite
model_dtype:
    value: bfloat16
multiple_models:
    value: 0
num_cont_rounds:
    value: 100
num_outputs_per_prompt:
    value: 8
num_rounds:
    value: 500
num_workers:
    value: 12
one_tuning:
    value: 1
percentile:
    value: 70
prefix:
    value: wandb_smoketest
programdatabaseConfig:
    value:
        functions_per_prompt: 2
        num_islands: 6
        temp: 10
        temp_sampling_flag: 1
project:
    value: EvoTune
run_identifier_name:
    value: tsp_granite_dpo
run_or_dev:
    value: dev
seed:
    value: 0
task:
    value:
        failed_score: -20000
        function_str_to_extract: heuristics
        identity_heuristic: 1
        initial_percentile: 0.3
        mem_limit_gb: 10
        programdatabaseConfig:
            temp: 10
        task_name: tsp
        timeout_period: 90
testset:
    value: testset
top_k_functions_for_test:
    value: 50
train:
    value:
        dpo_config:
            beta: 0.4
            f_alpha_divergence_coef: 1
            f_divergence_type: alpha_divergence
            gradient_accumulation_steps: 16
            gradient_checkpointing: 1
            learning_rate: 1e-05
            logging_steps: 1
            lr_scheduler_type: cosine
            max_seq_length: 6500
            num_train_epochs: 2
            per_device_train_batch_size: 2
            warmup_steps: 0
            weight_decay: 0.001
        dpo_strategy: 2
        finetuning_frequency: 400
        train_method_name: dpo
use_tgi:
    value: 0
use_vllm:
    value: 0
vllm_gpu_memory_utilization:
    value: 0.8
vllm_max_model_len:
    value: 8192
wandb:
    value: 1
wandb_name:
    value: wandb_smoketest/tsp_granite_dpo_0
